# Generated by Django 3.2.7 on 2021-12-05 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_shop', '0010_auto_20211004_2051'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, null=True, verbose_name='code')),
                ('display_name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rules', models.CharField(max_length=150, null=True, verbose_name='rules')),
            ],
            options={
                'verbose_name': 'delivery method',
                'verbose_name_plural': 'delivery methods',
                'db_table': 'delivery_methods',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, null=True, verbose_name='code')),
                ('display_name', models.CharField(max_length=50, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
                'db_table': 'payment_methods',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15, null=True, verbose_name='city')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='phone')),
                ('receiver_name', models.CharField(max_length=50, null=True, verbose_name='receiver name')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('payment_error', 'Payment error'), ('waiting_payment', 'Waiting payment')], default='draft', max_length=50, verbose_name='payment status')),
                ('delivery_method', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_cart.deliverymethod', verbose_name='delivery method')),
                ('payment_method', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_cart.paymentmethod', verbose_name='payment method')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70, verbose_name='product name')),
                ('count', models.IntegerField(default=1, verbose_name='count')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cart.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.product')),
            ],
        ),
    ]
