# Generated by Django 3.2.7 on 2021-12-05 18:59
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, serialize=False, verbose_name='uid'),
            preserve_default=False,
        ),
    ]
