# Generated by Django 3.2.7 on 2021-12-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', 'init_delivery_fill'),
        ('app_cart', 'init_payments'),
    ]

    operations = [
    ]
