# Generated by Django 3.2.7 on 2021-10-31 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rules', models.CharField(max_length=150, null=True, verbose_name='rules')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(max_length=15, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_cart.deliverymethod', verbose_name='delivery method'),
        ),
    ]
