# Generated by Django 3.2.7 on 2021-10-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0002_auto_20211031_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'ordering': ('id',), 'verbose_name': 'delivery method', 'verbose_name_plural': 'delivery methods'},
        ),
        migrations.AlterModelTable(
            name='deliverymethod',
            table='delivery_methods',
        ),
    ]
