# Generated by Django 3.2.7 on 2021-12-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0002_merge_init_delivery_fill_init_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(verbose_name = 'ID', serialize = False, auto_created = True, primary_key = True),
        ),
    ]
