# Generated by Django 3.2.7 on 2021-12-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0002_merge_init_delivery_fill_init_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
