# Generated by Django 3.2.7 on 2021-10-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0003_auto_20211031_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverymethod',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='code',
            field=models.CharField(max_length=15, null=True, verbose_name='code'),
        ),
    ]
