# Generated by Django 3.2.7 on 2022-03-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0004_auto_20211209_2205'),
    ]

    operations = [
    ]
