# Generated by Django 3.2.7 on 2021-11-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0004_auto_20211031_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('cart', 'Online cart'), ('random_account', 'Online from a random account')], default='p', max_length=50, verbose_name='payment method'),
        ),
    ]
