# Generated by Django 3.2.7 on 2021-11-07 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0005_auto_20211106_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.AddField(
            model_name='orders',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
