# Generated by Django 3.2.7 on 2022-03-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0005_auto_20220302_0007'),
    ]

    operations = [
    ]
