# Generated by Django 3.2.7 on 2021-11-07 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0006_auto_20211107_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='id'),
        ),
    ]
