# Generated by Django 3.2.7 on 2021-11-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0008_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='paid',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('payment_error', 'Payment error'), ('waiting_payment', 'Waiting payment')], default='draft', max_length=50, verbose_name='payment status'),
        ),
    ]
