# Generated by Django 3.2.7 on 2021-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0010_orderrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='count',
            field=models.IntegerField(default=1, verbose_name='count'),
        ),
    ]
