# Generated by Django 3.2.7 on 2021-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0012_orderrecord_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='product_name',
            field=models.CharField(max_length=70, verbose_name='product name'),
        ),
    ]
