# Generated by Django 3.2.7 on 2021-12-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0014_auto_20211204_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='display_name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='display_name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
