# Generated by Django 3.2.7 on 2021-12-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0015_auto_20211204_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_cart.paymentmethod', verbose_name='payment method'),
        ),
    ]
