# Generated by Django 3.2.7 on 2021-09-25 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shop', '0005_auto_20210923_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_properties',
            fields=[

                ('name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('value', models.CharField(max_length=50, null=True, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'db_table': 'shop_properties',
            },
        ),
    ]
