# Generated by Django 3.2.7 on 2021-09-25 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shop', '0006_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='email')),
                ('nickname', models.CharField(max_length=50, null=True, verbose_name='nickname')),
                ('text', models.TextField(verbose_name='text')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'deleted by admin')], default='p', max_length=1, verbose_name='status')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comments',
            },
        ),
    ]
