# Generated by Django 3.2.7 on 2021-09-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0008_product_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nickname'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'slug'], name='product_name_a1ffc8_idx'),
        ),
    ]
