# Generated by Django 3.2.7 on 2021-10-04 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0009_auto_20210929_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('value', models.CharField(max_length=250, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.product')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'db_table': 'props',
            },
        ),
        migrations.DeleteModel(
            name='shop_properties',
        ),
    ]
