# Generated by Django 3.2.7 on 2021-10-27 17:46

from django.db import migrations, models



class Migration(migrations.Migration):
    dependencies = [
        ('app_shop', '0010_auto_20211004_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('value', models.CharField(max_length=250, verbose_name='value')),
            ],
        )
    ]
