# Generated by Django 3.2.7 on 2021-10-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0011_settingssite'),
        ('app_shop', 'init_settings'),
    ]

    operations = [
    ]
