# Generated by Django 3.2.7 on 2021-10-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0012_merge_0011_settingssite_init_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingssite',
            options={'verbose_name': 'settings', 'verbose_name_plural': 'settings'},
        ),
        migrations.AlterModelTable(
            name='settingssite',
            table='settings',
        ),
    ]
