# Generated by Django 3.2.7 on 2021-10-31 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0013_auto_20211027_2145'),
        ('app_shop', 'init_delivery'),
    ]

    operations = [
    ]
