# Generated by Django 3.2.7 on 2021-10-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0014_merge_0013_auto_20211027_2145_init_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingsSite',
        ),
    ]
