# Generated by Django 3.2.7 on 2021-10-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0015_delete_settingssite'),
        ('app_shop', 'init_delivery_1'),
    ]

    operations = [
    ]
