# Generated by Django 3.2.7 on 2021-12-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0016_merge_0015_delete_settingssite_init_delivery_1'),
        ('app_shop', 'init_payments'),
    ]

    operations = [
    ]
