# Generated by Django 3.2.7 on 2021-09-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210922_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=170, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=170, verbose_name='description')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'db_table': 'tags',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotion',
        ),
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=True, verbose_name='free delivery'),
        ),
        migrations.AddField(
            model_name='product',
            name='hot_offers',
            field=models.BooleanField(default=False, verbose_name='hot offers'),
        ),
        migrations.AddField(
            model_name='product',
            name='limited_edition',
            field=models.BooleanField(default=False, verbose_name='limited edition'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='shop.Tags', verbose_name='tags'),
        ),
    ]
