version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    command: >
      sh -c "python3 manage.py migrate && python manage.py loaddata db4.json &&
             python3 manage.py runserver 0.0.0.0:3000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    container_name: 'app_db'
    env_file:
      - ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"
  redis:
    image: redis:alpine
    container_name: 'app_redis'
    ports:
      - "6379:6379"
  celery:
    build: .
    container_name: 'app_celery'
    command: celery -A megano  worker -l INFO --pool=solo
    volumes:
      - .:/code
    env_file:
      - ./.env
    links:
      - redis
    depends_on:
      - app
      - redis
volumes:
  pgdata: